#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensorOne, sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           metalClearGate, tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           dispenseWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           forkRight,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           dispenseGate,  tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           lightGate,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Group members: Jordy Mazza, Noah Canel, Adam Kalman
@author: Adam Kalman
Pseudocode:
Release one marble at a time
Use first light sensor to determine if marble is the black, rubber marble
If not black marble, sort to one area, where it will be deposited into proper bin
Bin to be placed into determined by light sensor value which will be compared to an array to determine which marble it is
If at inital sorting area, and it is a black marble, then send to ramp where it is dropped at an angle
Based on bounce of marble, it falls into apporpriate bin.
*/

int classifyMarble(int senseVal){
	if (senseVal<100){
		return 0;
	}
	else {
		return 3;
	}
}

task main()
{
	int fMetal=-20;
	int fClear=40;
	int gateOpen=63;
	int gateClose=-30;
	int despenserClose=0;
	int despenserOpen=40;
	int marblesRemaining=30; //How many are there?
	motor[flashlight]=127; //This should always be on
	while (marblesRemaining>0){
		motor[lightGate]=gateClose;
		motor[dispenseGate]=despenserOpen;
		wait1Msec(500);
		motor[dispenseGate]=despenserClose;
		wait1Msec(250);

		if(classifyMarble(SensorValue[lightSensorOne])==0){
			motor[metalClearGate]=fClear;
			motor[lightGate]=gateOpen;

		}
		else {
			motor[metalClearGate]=fMetal;
			motor[lightGate]=gateOpen;
		}
		wait1Msec(2000);

	}
}
