#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensorOne, sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           firstGate,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          dispenseWheel, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
Group members: Jordy Mazza, Noah Canel, Adam Kalman
Pseudocode:
Release one marble at a time
Use first light sensor to determine if marble is the black, rubber marble
If not black marble, sort to one area, where it will be deposited into proper bin
Bin to be placed into determined by light sensor value which will be compared to an array to determine which marble it is
If at inital sorting area, and it is a black marble, then send to ramp where it is dropped at an angle
Based on bounce of marble, it falls into apporpriate bin.
*/


void runMotor(tMotor myMotor, int speed, int time){
	/*
	Function to run a motor.
	Takes a motor, a integer of speed, and integer of time as parameters
	*/
	int currentSpeed=motor[myMotor];
	motor[myMotor]=speed;
	wait1Msec(time);
	motor[myMotor]=currentSpeed;

}
void classifyMarble(){
		int marbleLightValues[5]; //some number values for the light sensor to be filled in
		marbleLightValues[0]=0;
		marbleLightValues[1]=1;
		marbleLightValues[2]=2;
		marbleLightValues[3]=3;
		marbleLightValues[4]=4;
}

task main()
{
	runMotor(dispenseWheel, 63, 500);  //not sure speed and time, this will have to be tested and changed

}
